const LOAD_TODO_LIST = 'LOAD_TODO_LIST';
const ADD_TASK = 'ADD_TASK';
const DELETE_TASK = 'DELETE_TASK';
const TOGGLE_TASK = 'TOGGLE_TASK';
const MODIFY_TASK = 'MODIFY_TASK';
const TOGGLE_ALL_TASKS = 'TOGGLE_ALL_TASKS';
const CLEAR_COMPLETED = 'CLEAR_COMPLETED';

export {
  LOAD_TODO_LIST,
  ADD_TASK,
  DELETE_TASK,
  TOGGLE_TASK,
  MODIFY_TASK,
  TOGGLE_ALL_TASKS,
  CLEAR_COMPLETED
};
